// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hocbgkqkfuibcclmpdia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvY2Jna3FrZnVpYmNjbG1wZGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjYwMzMsImV4cCI6MjA2NzgwMjAzM30.ul4i7IkRbkg43gSmQ7T_yaD57TooDyRE_V3ztmkLjjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});